### ISSUE TITLE
MonacoEditor creates three divs instead of one after Dotnet Core 3.0 Preview 6 launched.

### ISSUE THREAD

**Issue by haavamoa** [Kyle-Undefined/Blazaco#6]
I have upgraded to the latest Dotnet Core 3.0 Preview-6. After the upgrade I notice that MonacoEditor creates three divs with three editors. They are not sharing the model and when I call `setValue` on it it only updates the first one.

Here is a screenshot of my visual tree from inspecting my site:

![image](https://user-images.githubusercontent.com/2527084/59797501-2013aa00-92e0-11e9-8b1b-d58b048c13cf.png)

**Comment by Kyle-Undefined** [comment]
Thanks for the info! I'm out of town right now but I'll be able to fix this when I get back and merge the current PR I haven't had the time to do so.

**Comment by haavamoa** [comment]
@Kyle-Undefined no worries, take it when you have the time for it. :wink:

**Comment by Kyle-Undefined** [comment]
@haavamoa Sorry for the delay, can you show me your Razor file? I've upgraded to Preview 6, and after changing my code to:

`<MonacoEditor @ref="_editor" Model="_editorModel" FullScreen="true" />`

I don't get the three editors, and I can use all the interops without issue. I use it for an internal project and I can't reproduce your issue.

Share what you can, and I can look into it.

**Comment by haavamoa** [comment]
I have to investigate it, because right now I cant reproduce the issue. Might have been my code :s

Here is the code :
https://github.com/haavamoa/Gjallarhorn/blob/master/src/Gjallarhorn.Client/Pages/SettingsPage.razor

**Comment by haavamoa** [comment]
Ah, the bug is still here in production. The link to the code is in the comments above.
