### ISSUE TITLE
Project still alive?

### ISSUE THREAD

**Issue by SirJson** [Kyle-Undefined/Blazaco#8]
Do you plan on continuing developing Blazaco or do you plan on abandoning the project? Right now this version won't work with Blazor WebAssembly but there are pull requests fixing the problem.

If you don't plan on further spending time in this project can I maintain it or are you okay with my fork? I don't think there is much to add to it yet. The only thing that I would do is making sure it still builds and works with Blazor WebAssembly until the public apis are stable.

**Comment by Kyle-Undefined** [comment]
Hey! Sorry things have been super crazy, I do still plan to support it I just haven't had the time. Sorry! I'll get right into this weekend since I will actually have the time to.

**Comment by Flearz** [comment]
Nice project, it will be very useful for mine, didn't find any component like this that is almost up to date. So if you update it when you have time it will be perfect 💃 
Happy Christmas time !

**Comment by Flearz** [comment]
@SirJson Could you please give me a simple working project? I tried to do it by mixing your fork and the original project but I got errors when loading the editor... Thanks in advance

**Comment by SirJson** [comment]
@Flearz I just uploaded a branch on my fork called "patched". It only contains all open PRs from the original repository and none of my modifications. This branch should build on your PC. I also made this branch the default for now to make it easier to use Blazaco.

https://github.com/SirJson/Blazaco

**Comment by paolofulgoni** [comment]
Any update on the project status?

**Comment by hawkerm** [comment]
@Kyle-Undefined I've been writing a C# wrapper for Monaco for UWP usage [here](https://github.com/hawkerm/monaco-editor-uwp). We should coordinate sometime to just share a .NET version of the types across projects somehow maybe?

**Comment by serdarciplak** [comment]
As this projects seems to be abandoned, please check this one out : [https://github.com/serdarciplak/BlazorMonaco](https://github.com/serdarciplak/BlazorMonaco)

**Comment by Kyle-Undefined** [comment]
Sorry, life got in the way. I've updated the readme to point to @serdarciplak repo as this is dead.
